### ISSUE TITLE
Adding `questionFormat` predicate

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#138]
Have anybody thought about adding a way to express axiom questions format in a specific language? Something like

```
(questionFormat instance "what is %1?")
(questionFormat subclass "what is a %1?")
```

. For the questions that aren't trivially derivable from the fact formats.

**Comment by apease** [comment]
Could you explain this further? If this is meant to mimic a human explanation, this requires a lot of intelligence.  Imagine pointing to an animal and asking "what is this"?  The agent could say "it is an animal" and that would be true but probably not useful.  It could similarly respond "it is a dog", which would only be useful in contexts where someone didn't know what a dog was.  But if the animal has dug up a flower bed, saying "it's my dog" is a useful admission of responsibility.

**Comment by apease** [comment]
intriguing idea but needs further development before we can specify what the action item is, closing the issue

**Comment by nordlow** [comment]
> intriguing idea but needs further development before we can specify what the action item is, closing the issue

What do you mean by "action item"?

**Comment by apease** [comment]
that's standard business speak for "what is the concrete task that needs doing"

**Comment by arademaker** [comment]
I agree that issues must be a concrete action item. Something should be supposed to be done to close the issue. Or we can create labels for general questions or ideas and mark the issues as such. 

Anyway, @nordlow, maybe you are talking about expression formally questions instead of only assertions? If this is your question, @apease has already an extension of SUO-KIF to deal with that: 

https://github.com/ontologyportal/sumo/blob/master/tests/TQG1.kif.tq#L7

**Comment by arademaker** [comment]
Following this line, in this [paper last year](https://arademaker.github.io/bibliography/gwc-2019-embeddings.html), together with Hugo from Portugal, we did a first experiment with the use of embeddings to train a simple model that recognizes question patterns and transforms them into queries about Wordnet relationships.
