### ISSUE TITLE
Microtheories for contextual knowledge

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#150]
Does SUMO have a predicate for expressing contextualized knowledge? (Open)Cyc supports this as described in [this paper](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=2ahUKEwj314Sj2NbgAhWBwqYKHecdCdgQFjABegQIAxAC&url=http%3A%2F%2Fwww.qrg.northwestern.edu%2Fnextkb%2FIntroOpenCycOnt.pdf&usg=AOvVaw1y-hkjyAC2-cXXpvrO505f).

Further, according to the paper, Cyc use the predicate `isa` for in-place of SUMO's `subclass` and `instance` in statements such as

```
(isa NeroTheCat Cat)
```

and

```
(isa Cat BiologicalSpecies)
(isa Cat DomesticatedAnimalType)
```

Is the author of the paper incorrect or doesn't Cyc distinguish subclass-of from instance-of relations?

**Comment by apease** [comment]
Hi Per,
  OpenCyc doesn't exist any more http://www.cyc.com/opencyc/ and I think only full Cyc had microtheories.  SUMO doesn't have such a mechanism since there doesn't appear to be a logically sound reasoning method for it or implementation in any major theorem prover, just a heuristic implementation.  I believe Cyc used the symbol "genls" for what SUMO calls subclass.  One approach to contextual reasoning in SUMO with differing assumptions is to separate common knowledge from what might call local or expert opinion into different KB files, then ask queries to the differing KBs that have different knowledge, much as one might poll experts at a conference where each has some differing assumptions that lead to different lines of reasoning and answers to complex questions.

all the best,
Adam

**Comment by nordlow** [comment]
Thanks.
