### ISSUE TITLE
`CellPartFn` 

### ISSUE THREAD

**Issue by arademaker** [ontologyportal/sumo#161]
Considering that we have already the declaration of the arguments and return types of the function CellPartFn:

```
(instance CellPartFn BinaryFunction)
(domain CellPartFn 1 Cell)
(domainSubclass CellPartFn 2 CellPart)
(range CellPartFn CellPart)
```

What these lines below are adding? We can see that the first axiom maybe formalizating the documentation of `CellPartFn`, but the second axioms looks redundant considering the definition of the range of CellPartFn.. what do you think?

```
(properPart (CellPartFn ?CELL ?PARTTYPE) ?CELL)
(instance (CellPartFn ?VIR ?PARTTYPE) ?PARTTYPE)
```

https://github.com/ontologyportal/sumo/blame/b3c95dbb1f8ab932d836154a536228f22e8ad257/VirusProteinAndCellPart.kif#L591

**Comment by apease** [comment]
(properPart (CellPartFn ?CELL ?PARTTYPE) ?CELL) is part of the definition of CellPartFn - any CellPartFn is a properPart.  The second axiom is also part of the definition of CellPartFn.  It states that any part of a cell of a particular type is an instance of that type.  So, for example
(instance (CellPartFn Nucleus1234567 CellNucleus) CellNucleus)

**Comment by whitten** [comment]
Adam, where did you get that axiom :  (properPart (CellPartFn ?CELL ?PARTTYPE) ?CELL)  ?

**Comment by apease** [comment]
(properPart    (CellPartFn ?CELL ?PARTTYPE) ?CELL) 
VirusProteinAndCellPart.kif 589-589 

http://sigma.ontologyportal.org:8080/sigma/Browse.jsp?kb=SUMO&lang=EnglishLanguage&flang=SUO-KIF&term=CellPartFn

**Comment by whitten** [comment]
Thank you for showing me that.
The cell part of a cell and a kind of cell part is an instance of a kind of cell part

There appears to be a bug in the "Englishizer" since I expected the first "cell part" phrase to be linked 
and not just the word "cell".  It links to CellPart so that works as I expected.    Do we have a test suite for the "sigma browser" code ?

Thanks again -- fascinating stuff to me.
