### ISSUE TITLE
create a contribution guideline on the wiki or in a file 

### ISSUE THREAD

**Issue by arademaker** [ontologyportal/sumo#168]
In the discussion about the `development` folder during the issue:

https://github.com/ontologyportal/sumo/issues/43#issuecomment-314128260

@msvarny said and I agree:

>  I think it would be worthwhile to have a discussion about the worklow and reach some agreement, that could be part of SUMO's documentation or ReadMe file so that every contributor could easily find guidance on how to join in.

People need to have clear information about how to contribute. This issue is about the creation of this guideline. Something like https://github.com/globalwordnet/english-wordnet/blob/master/CONTRIBUTING.md.

**Comment by SaveInProcess** [comment]
Perhaps the implementation of a roadmap about the possibilities and current situation about ontology and SUMO and their tools would be appropriate
What are the major drawbacks nowadays? Does SUMO could run at Windows environment?
The answers could improve, a lot, the SUMO users


________________________________
De: Alexandre Rademaker <notifications@github.com>
Enviado: Friday, June 28, 2019 11:53:41 AM
Para: ontologyportal/sumo
Cc: Subscribed
Assunto: [ontologyportal/sumo] create a contribution guideline on the wiki or in a file (#168)


In the discussion about the development folder during the issue:

#43 (comment)<https://github.com/ontologyportal/sumo/issues/43#issuecomment-314128260>

@msvarny<https://github.com/msvarny> said and I agree:

I think it would be worthwhile to have a discussion about the worklow and reach some agreement, that could be part of SUMO's documentation or ReadMe file so that every contributor could easily find guidance on how to join in.

People need to have clear information about how to contribute. This issue is about the creation of this guideline. Something like https://github.com/globalwordnet/english-wordnet/blob/master/CONTRIBUTING.md.

**Comment by arademaker** [comment]
@SaveInProcess SUMO is not executable! It is an ontology, not a system. [SigmaKEE](https://github.com/ontologyportal/sigmakee) is a system and, as far as I know, it runs at Windows operational system. 

I also believe that for the drawbacks, we have the issues. The open issues can be considered the problems waiting for be solved.

**Comment by apease** [comment]
That’s right @arademaker thanks for explaining. @saveinprocess glad to answer any questions you might have.  The introductory video at ontologyportal.org maybe also help with proving an orientation

**Comment by apease** [comment]
added a contribution guide for SUMO and will do one for SigmaKEE and SigmaNLP as well in the future https://github.com/ontologyportal/sumo/blob/master/CONTRIBUTING.md

**Comment by apease** [comment]
@SaveInProcess you might also look at http://www.adampease.org/OP/student.html which has some project ideas where people could contribute

**Comment by arademaker** [comment]
I am closing this issue since the guideline is in place.
