### ISSUE TITLE
wordnet mapping

### ISSUE THREAD

**Issue by arademaker** [ontologyportal/sumo#254]
http://wn.mybluemix.net/synset?id=08583292-n

(the line formed by the lower edge of a skirt or coat) - hemline

it is mapped to http://sigma.ontologyportal.org:8080/sigma/WordNet.jsp?synset=108583292&kb=SUMO&flang=SUO-KIF&lang=EnglishLanguage&kb=SUMO (subsuming mapping)

**Comment by apease** [comment]
a "hemline" is a Region -

(documentation Region EnglishLanguage "A topographic location. Regions encompass surfaces of Objects, imaginary places, and GeographicAreas. Note that a Region is the only kind of Object which can be located at itself. Note too that Region is not a subclass of SelfConnectedObject, because some Regions, e.g. archipelagos, have parts which are not connected with one another.")

That sounds right to me.  Is there an issue that you see with this current mapping that you could explain further?

**Comment by arademaker** [comment]
In the definitions using Region, it is mainly associated to topographic locations or geographic areas. But if this is a more abstract concept, fine and we can close. Maybe too abstract for the WN concept, but I don't have any better suggestion! ;-)

**Comment by arademaker** [comment]
Maybe part of a coat?

**Comment by apease** [comment]
A Region is any region of any Object.  Whether a Coat or Earth.  To be specific about a geographic region of Earth, use the concept GeographicRegion

**Comment by arademaker** [comment]
I see. But I am not talking about Region. I was just suggesting that a more specific mapping for hemline could be interesting.

**Comment by apease** [comment]
That could be handled with the relation 'part' of an 'Object' but if you think there's a reasonable class for parts of clothing I'd be very interested in its definition.  We could also define in SUMO the notion of a Hemline as a part of Clothing where the fabric is doubled up and sewn at the edge of a garment.  Would you like to try that?
