### ISSUE TITLE
Logical functions

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#90]
Can `and`, `or` and `not` be regarded as functions with boolean domain and range?

That is, could they just aswell have been named `andFn`, `orFn` and `notFn` instead?

**Comment by apease** [comment]
It's possible that in some computer language they could be named that way, and of course its the semantics that are really important rather than the names, but that would be a bit unusual and not in keeping with most logical languages, and could be confusing to those who work also in TPTP, Coq, or even Java.

**Comment by nordlow** [comment]
I was just checking that they can be regarded as functions from a semantic point of view. Thanks.

**Comment by apease** [comment]
answered questions, no action item, closing issue
