### ISSUE TITLE
Properties and attributes

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#94]
[This discussion](https://english.stackexchange.com/questions/150529/what-is-the-difference-between-property-and-attribute)

claims the follow usage example for the English words property and attribute:
"Jeff Atwood has the attribute black for the property hair color."

Is this compatible with SUMOs meaning of `property` and `attribute`?

Is this discussed in your book?

**Comment by apease** [comment]
Hi Per,

   There's some information on this in my book, but &%property and 
&%attribute are both relations.  They are often used as arguments to 
&%holdsDuring to limit their temporal scope. &%attribute is more 
specific than &%property in requiring an Object.  To say that Jeff has 
black hair we'd use the more specific &%color relation to say


(and

   (instance ?H Hair)

   (part ?H JeffAtwood)

   (color ?H Black))


all the best,

Adam

**Comment by nordlow** [comment]
Ok. I saw a note in the code that the `color` relation should be generalized by the `attribute` relation. Why the shism?

**Comment by apease** [comment]
Hi Per,

   I'm not sure what note you're referring to, although I may have 
myself argued in the past that &%color isn't needed, since it has very 
little to distinguish it from &%attribute other than that one argument 
is a ColorAttribute rather than just a generic Attribute.  But in 
practical terms it causes little trouble in terms of representation but 
can make the projection from language to a logical representation a 
little easier.


all the best,

Adam

**Comment by apease** [comment]
answered questions, no action item, closing issue
